import type { Metadata } from "next";
import "./globals.css";
import { lato } from "./ui/fonts";
import HeaderNav from "./header-nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased container`}>
        <HeaderNav />
        {children}
      </body>
    </html>
  );
}
